export const MEDICAL_CONSTANTS = Object.freeze({
  TXA_WINDOW_MIN: 180,
  TXA_WARN_THRESHOLD: 60,
  TQ_CRITICAL_SEC: 3000,
  TQ_WARN_SEC: 2400,
  MAX_VITALS_HISTORY: 10,
  MAX_TIMELINE_EVENTS: 500,
});